# Generated by Django 6.0 on 2025-12-24 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('all', 'Hammasi'), ('urganch1', 'Urganch 1'), ('urganch2', 'Urganch 2')], default='urganch1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Kirim'), ('out', 'Chiqim'), ('transfer', 'Kochirish'), ('adjustment', 'Tuzatish')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('branch', models.CharField(default='urganch1', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
