# Generated by Django 6.0 on 2026-01-05 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_branch_alter_stockmovement_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('m', 'Metr'), ('m2', 'Kvadrat metr'), ('m3', 'Kub metr'), ('l', 'Litr'), ('dona', 'Dona')], default='dona', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_package_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='opened_package_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ochilgan qop/rulondagi qoldiq (base_unit da)', max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_unit',
            field=models.CharField(choices=[('qop', 'Qop'), ('rulon', 'Rulon'), ('dona', 'Dona'), ('m', 'Metr'), ('m2', 'Kvadrat metr'), ('m3', 'Kub metr'), ('kg', 'Kilogram'), ('bank', 'Bank'), ('korobka', 'Korobka')], default='dona', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='short_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_ratio',
            field=models.DecimalField(decimal_places=3, default=1, help_text='1 sell_unit = ? base_unit (masalan: 1 qop = 25 kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity in base_unit', max_digits=15),
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('barcode_type', models.CharField(choices=[('factory', 'Zavod barcode'), ('package', 'Qop/Rulon barcode'), ('internal', 'Ichki barcode'), ('manual', 'Manual kod')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='products_ba_code_f2685f_idx')],
            },
        ),
    ]
