# Generated by Django 5.2.11 on 2026-02-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_sku_remove_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='branch',
        ),
    ]
