# Generated by Django 5.2.11 on 2026-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_branch_remove_stockmovement_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='dona', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_unit',
            field=models.CharField(default='dona', max_length=20),
        ),
    ]
