# Generated by Django 6.0 on 2026-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auto_block_on_limit',
            field=models.BooleanField(default=True, help_text='Limit oshganda avtomatik blok qilish'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('regular', 'Oddiy mijoz'), ('usta', 'Usta'), ('brigadir', 'Brigadir'), ('firma', 'Firma')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='debt_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = qarz olish mumkin emas', max_digits=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('blocked', 'Blocked'), ('blocked_by_debt', 'Blocked by Debt Limit')], default='active', max_length=20),
        ),
    ]
