# Generated by Django 5.2.11 on 2026-02-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_auto_block_on_limit_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
    ]
