# Generated by Django 6.0 on 2026-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='debt_signature_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_debt_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='keyboard_shortcut_used',
            field=models.CharField(blank=True, help_text='F8, F9, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='scanner_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='base_unit_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated quantity in base unit', max_digits=15),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='from_opened_package',
            field=models.BooleanField(default=False, help_text='Ochilgan qop/rulondan sotilganmi'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_ratio_at_sale',
            field=models.DecimalField(decimal_places=3, default=1, help_text='Conversion ratio at time of sale', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_type',
            field=models.CharField(choices=[('base', 'Base Unit'), ('sell', 'Sell Unit')], default='sell', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('debt', 'Qarz'), ('mixed', 'Aralash'), ('truck_sale', 'Mashina sotuvi')], max_length=20),
        ),
    ]
