# Generated by Django 6.0 on 2026-01-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_debt_signature_required_sale_is_debt_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma"), ('debt', 'Qarz'), ('mixed', 'Aralash'), ('truck_sale', 'Mashina sotuvi')], max_length=20),
        ),
    ]
