# Generated by Django 5.2.11 on 2026-02-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
    ]
