# Generated by Django 6.0 on 2025-12-24 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('sale', 'Savdo'), ('product_add', "Mahsulot qo'shildi"), ('product_edit', "Mahsulot o'zgartirildi"), ('price_change', "Narx o'zgartirildi"), ('stock_move', 'Ombor harakati'), ('debt_payment', "Qarz to'lovi"), ('setting_change', "Sozlama o'zgartirildi")], max_length=20)),
                ('description', models.TextField()),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='urganch1', max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Filial Admini'), ('seller', 'Sotuvchi'), ('warehouse_keeper', 'Omborchi')], default='seller', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
