# Generated by Django 6.0 on 2025-12-24 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_storesettings_alter_employee_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
    ]
