# Generated by Django 6.0 on 2026-01-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin',
            field=models.CharField(blank=True, help_text='POS login PIN', max_length=10, null=True, unique=True),
        ),
    ]
