# Generated by Django 5.2.11 on 2026-02-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_pin'),
        ('customers', '0004_remove_customer_branch'),
        ('products', '0004_remove_product_branch_remove_stockmovement_branch'),
        ('sales', '0005_remove_sale_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='branch',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Dukon Admini'), ('seller', 'Sotuvchi'), ('warehouse_keeper', 'Omborchi')], default='seller', max_length=20),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
